### ISSUE TITLE
Error on forced downloads

### ISSUE THREAD

**Issue by Gabisonfire** [esanchezm/prometheus-qbittorrent-exporter#3]
`ValueError: 'forcedDL' is not a valid TorrentStates`

Got this because I have a torrent in "Forced Downloading", might be some missing states.

**Comment by esanchezm** [comment]
I was able to reproduce it. However, I think it's a bug in [qbittorrent-api](https://github.com/rmartin16/qbittorrent-api) because if you look at the states definition, you'll see it's called `forceDL` and not `forcedDL`:

https://github.com/rmartin16/qbittorrent-api/blob/master/qbittorrentapi/definitions.py#L62

I suggest you to open a bug there. I don't follow qbittorrent development but maybe there was an API change and they need to adapt the library. Once that is fixed and released I can update the library to use that version, but I think doing a dirty hack to fix a problem upstream is not ideal.

```
/usr/lib64/python3.8/enum.py in __call__(cls, value, names, module, qualname, type, start)
    313         """
    314         if names is None:  # simple value lookup
--> 315             return cls.__new__(cls, value)
    316         # otherwise, functional API: we're creating a new Enum type
    317         return cls._create_(value, names, module=module, qualname=qualname, type=type, start=start)

/usr/lib64/python3.8/enum.py in __new__(cls, value)
    615             ve_exc = ValueError("%r is not a valid %s" % (value, cls.__name__))
    616             if result is None and exc is None:
--> 617                 raise ve_exc
    618             elif exc is None:
    619                 exc = TypeError(

ValueError: 'forcedDL' is not a valid TorrentStates

```

**Comment by Gabisonfire** [comment]
Good catch, I'll dig a bit more into it and submit a bug there.

**Comment by angristan** [comment]
I have opened a PR: https://github.com/rmartin16/qbittorrent-api/pull/48

**Comment by h3mmy** [comment]
I've just run into this issue again. Not exactly sure why.
```
{"asctime": "2022-04-30 20:52:02", "levelname": "INFO", "message": "Exporter is starting up"}
ValueError: 'forcedDL' is not a valid TorrentStates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qbittorrent-exporter", line 11, in <module>
    load_entry_point('prometheus-qbittorrent-exporter==1.1.0', 'console_scripts', 'qbittorrent-exporter')()
  File "/usr/lib/python3.8/site-packages/qbittorrent_exporter/exporter.py", line 198, in main
    REGISTRY.register(QbittorrentMetricsCollector(config))
  File "/usr/lib/python3.8/site-packages/prometheus_client/registry.py", line 26, in register
    names = self._get_names(collector)
  File "/usr/lib/python3.8/site-packages/prometheus_client/registry.py", line 66, in _get_names
    for metric in desc_func():
  File "/usr/lib/python3.8/site-packages/qbittorrent_exporter/exporter.py", line 45, in collect
    metrics = self.get_qbittorrent_metrics()
  File "/usr/lib/python3.8/site-packages/qbittorrent_exporter/exporter.py", line 64, in get_qbittorrent_metrics
    metrics.extend(self.get_qbittorrent_torrent_tags_metrics())
  File "/usr/lib/python3.8/site-packages/qbittorrent_exporter/exporter.py", line 132, in get_qbittorrent_torrent_tags_metrics
    status_torrents = [
  File "/usr/lib/python3.8/site-packages/qbittorrent_exporter/exporter.py", line 133, in <listcomp>
    t for t in category_torrents if getattr(TorrentStates, status_prop).fget(TorrentStates(t['state']))
  File "/usr/lib/python3.8/enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 595, in __new__
    raise exc
  File "/usr/lib/python3.8/enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.8/enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'forcedDL' is not a valid TorrentStates
```

**Comment by h3mmy** [comment]
Figured it out. API was inaccessible due to a different issue which in turn caused this error. exporter is fine.
