### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

### ISSUE THREAD

**Issue by Floo33R** [esanchezm/prometheus-qbittorrent-exporter#39]
Hello,
i tried to install this on my instance, but sadly it is not working. The goal would be to deploy it without the docker container. 

How to reproduce it on my side:
Install:
```
jellyfin@jellyfin:~$ pip3 install prometheus-qbittorrent-exporter
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: prometheus-qbittorrent-exporter in /usr/local/lib/python3.10/dist-packages (1.2.0)
Requirement already satisfied: python-json-logger==0.1.5 in ./.local/lib/python3.10/site-packages (from prometheus-qbittorrent-exporter) (0.1.5)
Requirement already satisfied: attrdict==2.0.1 in ./.local/lib/python3.10/site-packages (from prometheus-qbittorrent-exporter) (2.0.1)
Requirement already satisfied: qbittorrent-api==2021.3.18 in ./.local/lib/python3.10/site-packages (from prometheus-qbittorrent-exporter) (2021.3.18)
Requirement already satisfied: prometheus-client==0.8.0 in ./.local/lib/python3.10/site-packages (from prometheus-qbittorrent-exporter) (0.8.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from attrdict==2.0.1->prometheus-qbittorrent-exporter) (1.16.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from python-json-logger==0.1.5->prometheus-qbittorrent-exporter) (59.6.0)
Requirement already satisfied: requests>=2.16.0 in /usr/lib/python3/dist-packages (from qbittorrent-api==2021.3.18->prometheus-qbittorrent-exporter) (2.25.1)
Requirement already satisfied: urllib3>=1.24.2 in /usr/lib/python3/dist-packages (from qbittorrent-api==2021.3.18->prometheus-qbittorrent-exporter) (1.26.5)

```

Run it:
```
jellyfin@jellyfin:~$ qbittorrent-exporter
Traceback (most recent call last):
  File "/usr/local/bin/qbittorrent-exporter", line 5, in <module>
    from qbittorrent_exporter.exporter import main
  File "/usr/local/lib/python3.10/dist-packages/qbittorrent_exporter/exporter.py", line 6, in <module>
    from attrdict import AttrDict
  File "/home/jellyfin/.local/lib/python3.10/site-packages/attrdict/__init__.py", line 5, in <module>
    from attrdict.mapping import AttrMap
  File "/home/jellyfin/.local/lib/python3.10/site-packages/attrdict/mapping.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

I am using the following python version:
```
jellyfin@jellyfin:~$ python3 --version
Python 3.10.12
```

**Comment by esanchezm** [comment]
Hello @Floo33R,

We support Python >= 3.11. Could you please upgrade and try again?

Also, let me recommend you the Docker version, that should be pretty straightforward to use

**Comment by Floo33R** [comment]
Hi @esanchezm,
i tried this already serveral times. I found out that i messed up with the version of python and python3. 
Now it is working, thank you!

I cannot use the docker container, because I deployed the qBittorrent directly and at the moment there is no Docker running on this server. Maybe a future option :D
