### ISSUE TITLE
ModuleNotFoundError: No module named 'attrdict'

### ISSUE THREAD

**Issue by sognen** [esanchezm/prometheus-qbittorrent-exporter#7]
Hi,
I am getting a missing module with the latest pull:

Traceback (most recent call last):
  File "/usr/bin/qbittorrent-exporter", line 33, in <module>
    sys.exit(load_entry_point('prometheus-qbittorrent-exporter==1.1.1', 'console_scripts', 'qbittorrent-exporter')())
  File "/usr/bin/qbittorrent-exporter", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/qbittorrent_exporter/exporter.py", line 6, in <module>
    from attrdict import AttrDict
ModuleNotFoundError: No module named 'attrdict'

**Comment by esanchezm** [comment]
@sognen are you using the docker image?

**Comment by sognen** [comment]
> @sognen are you using the docker image?

Yes.

**Comment by sognen** [comment]
Thanks, I no longer get the module missing error.
